### PR TITLE
Changed WRAP to work with newest numpy

### LINKED ISSUE #60: ValueError due to shapely update
shapely recently updated with a breaking change.  I think this occured with version 2.0.0 of shapely
```
tz = tzwhere.tzwhere()
File "/usr/local/lib/python3.10/site-packages/tzwhere/tzwhere.py", line 62, in __init__
self.timezoneNamesToPolygons[tzname] = WRAP(polys)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (1, 2) + inhomogeneous part.
```

### PR DESCRIPTION
**Pull request by domas-v**
This should fix https://github.com/pegler/pytzwhere/issues/60

### CODE REVIEW

**Review by oxfn — APPROVED** [review]

**Comment by yalla** [comment]
Any chance that this one will be merged at some point? I manually changed in my local installations and I can confirm it works.

**Comment by pgAdmin** [comment]
@oxfn @domas-v What is holding up the merge ?

**Comment by domas-v** [comment]
Sorry, I cannot merge, don't have write access to the repository.

**Comment by werlex** [comment]
@pegler this PR needs to be merged in order to fix https://github.com/pegler/pytzwhere/issues/60

**Review by oxfn — APPROVED** [review]

**Comment by domas-v** [comment]
@oxfn, thanks for approving. Could you merge it as well?

**Comment by oxfn** [comment]
No, I'm not a member of this repo

**Pull request closed without merging**
